Repository esp-rs/esp-hal, pull requests merged in 2024-09, with the labels that each got.

#2015 QSPI tests
  hil-test/Cargo.toml
  hil-test/tests/qspi_read.rs
  hil-test/tests/qspi_write.rs
  hil-test/tests/qspi_write_read.rs
Labels: skip-changelog

#2048 Clean up gigantic GPIO eyesore
  esp-hal/src/soc/esp32/gpio.rs
  esp-hal/src/soc/esp32s2/gpio.rs
Labels: skip-changelog

#2060 Release preperation for xtensa-lx-rt@0.17.1
  .github/workflows/changelog.yml
  esp-backtrace/src/lib.rs
  esp-hal/CHANGELOG.md
  xtensa-lx-rt/CHANGELOG.md
  xtensa-lx-rt/Cargo.toml
Labels: skip-changelog

#2051 Protect SYSTIMER/TIMG shared registers
  esp-hal/src/lib.rs
  esp-hal/src/timer/systimer.rs
  esp-hal/src/timer/timg.rs
Labels: skip-changelog

#2062 Fix hil-test xtask instruction
  hil-test/README.md
Labels: documentation, skip-changelog

#2058 storage: Clean up ROM function declarations
  esp-storage/src/common.rs
  esp-storage/src/esp32.rs
  esp-storage/src/esp32c2.rs
  esp-storage/src/esp32c3.rs
  esp-storage/src/esp32c6.rs
  esp-storage/src/esp32h2.rs
  esp-storage/src/esp32s2.rs
  esp-storage/src/esp32s3.rs
  esp-storage/src/lib.rs
  esp-storage/src/ll.rs
  esp-storage/src/stub.rs
Labels: skip-changelog

#2004 WPA2 ENTERPRISE
  esp-ieee802154/Cargo.toml
  esp-ieee802154/src/compat/mod.rs
  esp-ieee802154/src/compat/str_buf.rs
  esp-wifi/CHANGELOG.md
  esp-wifi/Cargo.toml
  esp-wifi/src/ble/btdm.rs
  esp-wifi/src/ble/npl.rs
  esp-wifi/src/common_adapter/mod.rs
  esp-wifi/src/compat/common.rs
  esp-wifi/src/compat/malloc.rs
  esp-wifi/src/compat/misc.rs
  esp-wifi/src/compat/mod.rs
  esp-wifi/src/compat/syslog.rs
  esp-wifi/src/compat/task_runner.rs
  esp-wifi/src/lib.rs
  esp-wifi/src/preempt/mod.rs
  esp-wifi/src/preempt/preempt_riscv.rs
  esp-wifi/src/preempt/preempt_xtensa.rs
  esp-wifi/src/tasks.rs
  esp-wifi/src/timer/riscv.rs
  esp-wifi/src/timer/xtensa.rs
  esp-wifi/src/wifi/mod.rs
  esp-wifi/src/wifi/os_adapter.rs
Labels: skip-changelog

#2023 Adding `I2C` HIL test
  hil-test/Cargo.toml
  hil-test/README.md
  hil-test/src/lib.rs
  hil-test/tests/gpio.rs
  hil-test/tests/i2c.rs
  hil-test/tests/i2s.rs
  hil-test/tests/i2s_async.rs
  hil-test/tests/pcnt.rs
  hil-test/tests/qspi_read.rs
  hil-test/tests/qspi_write.rs
  hil-test/tests/qspi_write_read.rs
  hil-test/tests/rmt.rs
  hil-test/tests/spi_full_duplex.rs
  hil-test/tests/spi_full_duplex_dma.rs
  hil-test/tests/spi_full_duplex_dma_async.rs
  hil-test/tests/spi_full_duplex_dma_pcnt.rs
  hil-test/tests/spi_half_duplex_read.rs
  hil-test/tests/spi_half_duplex_write.rs
  hil-test/tests/twai.rs
  hil-test/tests/uart.rs
  hil-test/tests/uart_async.rs
  hil-test/tests/uart_tx_rx.rs
  hil-test/tests/uart_tx_rx_async.rs
Labels: tests

#2069 Remove gpio dispatch macro-defining proc macro
  esp-hal-procmacros/src/enum_dispatch.rs
  esp-hal-procmacros/src/lib.rs
  esp-hal/src/gpio/mod.rs
Labels: skip-changelog

#2082 Fix nightly warnings
  esp-hal/src/aes/mod.rs
  esp-hal/src/i2s.rs
  esp-hal/src/parl_io.rs
  esp-hal/src/spi/slave.rs
Labels: skip-changelog

#2078 Build examples in debug mode
  .github/actions/check-esp-hal/action.yml
  .github/workflows/ci.yml
  esp-storage/build.rs
  examples/build.rs
  examples/src/bin/embassy_rmt_rx.rs
  examples/src/bin/psram_octal.rs
  examples/src/bin/psram_quad.rs
  xtask/src/cargo.rs
  xtask/src/lib.rs
  xtask/src/main.rs
Labels: skip-changelog

#2091 Rename `esp_hal::time::current_time` to `esp_hal::time::now`
  esp-hal-embassy/src/time_driver.rs
  esp-hal/CHANGELOG.md
  esp-hal/MIGRATING-0.20.md
  esp-hal/src/delay.rs
  esp-hal/src/lib.rs
  esp-hal/src/soc/esp32/mod.rs
  esp-hal/src/soc/esp32c2/mod.rs
  esp-hal/src/soc/esp32c3/mod.rs
  esp-hal/src/soc/esp32c6/mod.rs
  esp-hal/src/soc/esp32h2/mod.rs
  esp-hal/src/soc/esp32s2/mod.rs
  esp-hal/src/soc/esp32s3/mod.rs
  esp-hal/src/time.rs
  esp-hal/src/timer/systimer.rs
  esp-hal/src/timer/timg.rs
  esp-wifi/src/timer/riscv.rs
  esp-wifi/src/timer/xtensa.rs
  examples/src/bin/timer_interrupt.rs
  hil-test/tests/delay.rs
  hil-test/tests/embassy_timers_executors.rs
  hil-test/tests/get_time.rs
Labels: skip-changelog

#2100 Update esp-println version in usage section
  esp-println/README.md
Labels: skip-changelog

#2104 Ensure that clock init happens after Rtc domain is initialized
  esp-hal/src/lib.rs
Labels: skip-changelog

#2099 esp-wifi uses global allocator, esp-alloc supports multiple regions
  esp-alloc/CHANGELOG.md
  esp-alloc/Cargo.toml
  esp-alloc/src/lib.rs
  esp-alloc/src/macros.rs
  esp-hal/src/soc/esp32s2/psram.rs
  esp-hal/src/soc/esp32s3/psram.rs
  esp-wifi/CHANGELOG.md
  esp-wifi/Cargo.toml
  esp-wifi/MIGRATING-0.9.md
  esp-wifi/README.md
  esp-wifi/src/compat/malloc.rs
  esp-wifi/src/lib.rs
  esp-wifi/src/wifi/os_adapter.rs
  esp-wifi/tuning.md
  examples/Cargo.toml
  examples/src/bin/dma_extmem2mem.rs
  examples/src/bin/psram_octal.rs
  examples/src/bin/psram_quad.rs
  examples/src/bin/wifi_80211_tx.rs
  examples/src/bin/wifi_access_point.rs
  examples/src/bin/wifi_access_point_with_sta.rs
  examples/src/bin/wifi_bench.rs
  examples/src/bin/wifi_ble.rs
  examples/src/bin/wifi_coex.rs
  examples/src/bin/wifi_dhcp.rs
  examples/src/bin/wifi_embassy_access_point.rs
  examples/src/bin/wifi_embassy_access_point_with_sta.rs
  examples/src/bin/wifi_embassy_bench.rs
  examples/src/bin/wifi_embassy_ble.rs
  examples/src/bin/wifi_embassy_dhcp.rs
  examples/src/bin/wifi_embassy_esp_now.rs
  examples/src/bin/wifi_embassy_esp_now_duplex.rs
  examples/src/bin/wifi_esp_now.rs
  examples/src/bin/wifi_sniffer.rs
  examples/src/bin/wifi_static_ip.rs
  xtask/src/main.rs
Labels: skip-changelog

#2109 Touch pin definition overhaul
  esp-hal/CHANGELOG.md
  esp-hal/src/gpio/mod.rs
  esp-hal/src/soc/esp32/gpio.rs
Labels: skip-changelog

#2126 Make sure we can compile with `defmt`
  .github/workflows/ci.yml
  .github/workflows/ci_nightly.yml
  esp-hal/src/soc/esp32/psram.rs
  esp-wifi/Cargo.toml
  esp-wifi/src/ble/controller/mod.rs
Labels: skip-changelog

#2124 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: skip-changelog

#2130 Fix Matrix link
  .github/ISSUE_TEMPLATE/config.yml
Labels: skip-changelog

#2139 Fix I2S examples
  esp-hal/MIGRATING-0.20.md
  examples/src/bin/embassy_i2s_read.rs
  examples/src/bin/embassy_i2s_sound.rs
  examples/src/bin/embassy_parl_io_rx.rs
  examples/src/bin/embassy_parl_io_tx.rs
  examples/src/bin/i2s_read.rs
  examples/src/bin/i2s_sound.rs
  examples/src/bin/lcd_cam_ov2640.rs
  examples/src/bin/lcd_i8080.rs
  examples/src/bin/parl_io_rx.rs
  examples/src/bin/parl_io_tx.rs
  examples/src/bin/qspi_flash.rs
Labels: skip-changelog

#2140 Enable SPI_DMA_XX_ASYNC and _PCNT tests on ESP32 and S2, remove GPIO …
  hil-test/tests/gpio.rs
  hil-test/tests/i2c.rs
  hil-test/tests/i2s.rs
  hil-test/tests/i2s_async.rs
  hil-test/tests/pcnt.rs
  hil-test/tests/qspi_read.rs
  hil-test/tests/qspi_write.rs
  hil-test/tests/qspi_write_read.rs
  hil-test/tests/rmt.rs
  hil-test/tests/spi_full_duplex.rs
  hil-test/tests/spi_full_duplex_dma.rs
  hil-test/tests/spi_full_duplex_dma_async.rs
  hil-test/tests/spi_full_duplex_dma_pcnt.rs
  hil-test/tests/spi_half_duplex_read.rs
  hil-test/tests/spi_half_duplex_write.rs
  hil-test/tests/twai.rs
  hil-test/tests/uart.rs
  hil-test/tests/uart_async.rs
  hil-test/tests/uart_tx_rx.rs
  hil-test/tests/uart_tx_rx_async.rs
Labels: skip-changelog

#2110 GPIO user interrupt tweaks
  esp-hal/src/gpio/dummy_pin.rs
  esp-hal/src/gpio/mod.rs
  esp-hal/src/interrupt/mod.rs
  examples/src/bin/gpio_interrupt.rs
Labels: skip-changelog

#2144 Rename and wrap ErasedTimer
  esp-hal-embassy/src/lib.rs
  esp-hal-embassy/src/time_driver.rs
  esp-hal/CHANGELOG.md
  esp-hal/MIGRATING-0.20.md
  esp-hal/src/timer/mod.rs
  esp-wifi/src/lib.rs
  examples/src/bin/embassy_multicore.rs
  examples/src/bin/embassy_multicore_interrupt.rs
  examples/src/bin/embassy_multiprio.rs
  examples/src/bin/wifi_80211_tx.rs
  examples/src/bin/wifi_sniffer.rs
  hil-test/tests/embassy_interrupt_spi_dma.rs
  hil-test/tests/embassy_timers_executors.rs
Labels: skip-changelog

#2153 one typo; one misleading comment fixed
  esp-hal/src/timer/systimer.rs
  examples/src/bin/i2c_display.rs
Labels: skip-changelog

#2152 Fix DMA starving SPI
  esp-hal/src/spi/master.rs
  hil-test/tests/spi_full_duplex_dma.rs
Labels: skip-changelog

#2163 Fix esp_alloc doc
  esp-alloc/src/lib.rs
Labels: skip-changelog

#2157 Gpio cleanup
  esp-hal/src/gpio/etm.rs
  esp-hal/src/gpio/interconnect.rs
  esp-hal/src/gpio/mod.rs
  esp-hal/src/rtc_cntl/sleep/esp32c6.rs
  esp-hal/src/rtc_cntl/sleep/esp32s3.rs
  esp-hal/src/soc/esp32/gpio.rs
  esp-hal/src/soc/esp32c2/gpio.rs
  esp-hal/src/soc/esp32c3/gpio.rs
  esp-hal/src/soc/esp32c6/gpio.rs
  esp-hal/src/soc/esp32h2/gpio.rs
  esp-hal/src/soc/esp32s2/gpio.rs
  esp-hal/src/soc/esp32s3/gpio.rs
Labels: skip-changelog

#2165 Be more clear about the `esp-alloc` feature in esp-wifi's migration g…
  esp-wifi/MIGRATING-0.9.md
Labels: skip-changelog

#2158 Slight timer cleanup
  esp-hal/src/lib.rs
  esp-hal/src/timer/timg.rs
Labels: skip-changelog

#2169 Remove the `esp-hal-smartled` package and `hello_rgb` example
  .github/workflows/changelog.yml
  Cargo.toml
  esp-hal-smartled/CHANGELOG.md
  esp-hal-smartled/Cargo.toml
  esp-hal-smartled/README.md
  esp-hal-smartled/src/lib.rs
  examples/Cargo.toml
  examples/src/bin/hello_rgb.rs
  xtask/src/lib.rs
  xtask/src/main.rs
Labels: skip-changelog

#2168 Migration guide fixes
  esp-hal/MIGRATING-0.20.md
Labels: skip-changelog

#2172 Use esp types in peripheral docs
  esp-hal/src/peripheral.rs
Labels: skip-changelog

#2148 Tweak xtensa interrupt handling
  esp-hal/src/interrupt/xtensa.rs
Labels: skip-changelog

#2176 Guide: Clarify that Level can be used as an output signal
  esp-hal/MIGRATING-0.20.md
  esp-hal/src/gpio/placeholder.rs
Labels: skip-changelog

#2188 Pass --verify when running HIL tests
  xtask/src/main.rs
Labels: CI

#2184 Remove Debug2Format from esp-hal
  esp-hal/src/lib.rs
Labels: skip-changelog

#2190 Some minor I2S cleanups
  esp-hal/src/dma/mod.rs
  esp-hal/src/i2s.rs
  hil-test/Cargo.toml
  hil-test/tests/i2s.rs
  hil-test/tests/i2s_async.rs
Labels: skip-changelog

#2180 Allow configuring the watchdogs in the init config
  esp-hal-embassy/MIGRATING-0.3.md
  esp-hal/CHANGELOG.md
  esp-hal/MIGRATING-0.20.md
  esp-hal/src/config.rs
  esp-hal/src/lib.rs
  esp-hal/src/rtc_cntl/mod.rs
  esp-wifi/MIGRATING-0.9.md
  hil-test/Cargo.toml
  hil-test/tests/init.rs
Labels: skip-changelog

#2200 Slight general cleanup, enable dma-macros test, allow using virtual mem2mem channel on c2
  esp-hal-embassy/CHANGELOG.md
  esp-hal-embassy/Cargo.toml
  esp-hal-embassy/src/time_driver.rs
  esp-hal/src/dma/gdma.rs
  esp-hal/src/dma/mod.rs
  esp-hal/src/dma/pdma.rs
  esp-hal/src/gpio/mod.rs
  esp-hal/src/i2c.rs
  esp-hal/src/i2s.rs
  esp-hal/src/peripheral.rs
  esp-hal/src/rmt.rs
  esp-hal/src/timer/systimer.rs
  esp-hal/src/touch.rs
  esp-hal/src/twai/mod.rs
  esp-hal/src/uart.rs
  hil-test/tests/dma_macros.rs
  hil-test/tests/dma_mem2mem.rs
  hil-test/tests/spi_half_duplex_read.rs
Labels: skip-changelog

#2178 Remove most PSRAM features
  esp-alloc/src/macros.rs
  esp-hal/CHANGELOG.md
  esp-hal/Cargo.toml
  esp-hal/MIGRATING-0.20.md
  esp-hal/build.rs
  esp-hal/src/lib.rs
  esp-hal/src/lock.rs
  esp-hal/src/soc/esp32/mod.rs
  esp-hal/src/soc/esp32/psram.rs
  esp-hal/src/soc/esp32s2/mod.rs
  esp-hal/src/soc/esp32s2/psram.rs
  esp-hal/src/soc/esp32s3/mod.rs
  esp-hal/src/soc/esp32s3/psram.rs
  esp-hal/src/soc/mod.rs
  esp-hal/src/soc/psram_common.rs
  esp-metadata/devices/esp32s3.toml
  examples/Cargo.toml
  examples/src/bin/dma_extmem2mem.rs
  examples/src/bin/psram_octal.rs
  examples/src/bin/psram_quad.rs
  xtask/src/lib.rs
  xtask/src/main.rs
Labels: skip-changelog

#2210 Apply rustfmt fix
  esp-wifi/src/wifi/mod.rs
Labels: skip-changelog

#2198 Enable QSPI tests on ESP32 and clean up
  esp-hal/src/spi/master.rs
  hil-test/Cargo.toml
  hil-test/src/lib.rs
  hil-test/tests/qspi.rs
  hil-test/tests/qspi_read.rs
  hil-test/tests/qspi_write.rs
  hil-test/tests/qspi_write_read.rs
Labels: skip-changelog

#2175 Add chip-specific features for tests/examples
  esp-metadata/src/lib.rs
  xtask/src/lib.rs
Labels: skip-changelog

#2205 Remove DMA RegisterAccess::init_channel
  esp-hal/src/aes/mod.rs
  esp-hal/src/dma/gdma.rs
  esp-hal/src/dma/mod.rs
  esp-hal/src/dma/pdma.rs
  esp-hal/src/i2s.rs
  esp-hal/src/lcd_cam/cam.rs
  esp-hal/src/lcd_cam/lcd/i8080.rs
  esp-hal/src/parl_io.rs
  esp-hal/src/soc/esp32s2/mod.rs
  esp-hal/src/spi/master.rs
  esp-hal/src/spi/slave.rs
Labels: skip-changelog

#2215 Simplify DMA interrupt handlers
  esp-hal/src/dma/mod.rs
Labels: skip-changelog

#2204 esp-config: allow negative values
  esp-config/src/generate.rs
  esp-config/src/lib.rs
  esp-wifi/build.rs
Labels: skip-changelog

#2220 Remove ChannelTypes trait
  esp-hal/src/dma/gdma.rs
  esp-hal/src/dma/mod.rs
  esp-hal/src/dma/pdma.rs
Labels: skip-changelog

#2209 Prevent reentry on single-core, add basic tests
  esp-hal/src/lib.rs
  esp-hal/src/soc/mod.rs
  esp-hal/src/sync.rs
  esp-hal/src/timer/systimer.rs
  esp-hal/src/timer/timg.rs
  hil-test/Cargo.toml
  hil-test/tests/critical_section.rs
Labels: skip-changelog

#2225 Remove TxPrivate and RxPrivate
  esp-hal/src/aes/mod.rs
  esp-hal/src/dma/gdma.rs
  esp-hal/src/dma/mod.rs
  esp-hal/src/i2s.rs
  esp-hal/src/lcd_cam/cam.rs
  esp-hal/src/lcd_cam/lcd/i8080.rs
  esp-hal/src/parl_io.rs
  esp-hal/src/spi/master.rs
  esp-hal/src/spi/slave.rs
Labels: skip-changelog

#2226 DMA macro cleanup
  esp-hal/src/dma/mod.rs
  hil-test/tests/qspi.rs
Labels: skip-changelog

#2223 Deduplicate half duplex SPI setup
  esp-hal/src/spi/master.rs
Labels: skip-changelog

#2230 Fix warning: 'creating a shared reference to mutable static is discouraged'
  esp-hal/src/clock/mod.rs
Labels: skip-changelog

#2218 Allow building docs from different tags
  .github/workflows/documentation.yml
  xtask/src/main.rs
Labels: skip-changelog

#2236 Add stop_transfer method to DMA driver
  esp-hal/src/dma/gdma.rs
  esp-hal/src/dma/mod.rs
  esp-hal/src/dma/pdma.rs
Labels: skip-changelog

#2241 Only lock once in `is_slice_in_psram`, use `usize` and fix a few comparisons
  esp-hal/src/dma/gdma.rs
  esp-hal/src/dma/mod.rs
  esp-hal/src/soc/esp32/mod.rs
  esp-hal/src/soc/esp32c2/mod.rs
  esp-hal/src/soc/esp32c3/mod.rs
  esp-hal/src/soc/esp32c6/mod.rs
  esp-hal/src/soc/esp32h2/mod.rs
  esp-hal/src/soc/esp32s2/mod.rs
  esp-hal/src/soc/esp32s3/mod.rs
  esp-hal/src/soc/mod.rs
Labels: skip-changelog

#2219 DMA: Deduplicate descriptor operations
  esp-hal/src/dma/mod.rs
Labels: skip-changelog
