Repository esp-rs/esp-hal, pull requests merged in 2024-10, with the labels that each got.

#2265 Fix eh0.2 `set_high`/`set_low`
  esp-hal/src/gpio/mod.rs
  hil-test/tests/gpio.rs
Labels: skip-changelog

#2266 Mindless SPI slave cleanup
  esp-hal/src/spi/slave.rs
Labels: skip-changelog

#2267 Move DMA buffers to a different file
  esp-hal/src/dma/buffers.rs
  esp-hal/src/dma/mod.rs
Labels: skip-changelog

#2272 Fix Rx/Tx order in SPI slave driver
  esp-hal/src/gpio/interconnect.rs
  esp-hal/src/spi/slave.rs
  hil-test/Cargo.toml
  hil-test/tests/spi_slave.rs
Labels: skip-changelog

#2251 esp-wifi: Align default settings
  esp-wifi/Cargo.toml
  esp-wifi/build.rs
  esp-wifi/src/lib.rs
  esp-wifi/src/wifi/mod.rs
Labels: skip-changelog

#2275 Clean up a bit
  esp-hal/src/dma/gdma.rs
  esp-hal/src/dma/mod.rs
  esp-hal/src/dma/pdma.rs
  esp-hal/src/i2s.rs
  esp-hal/src/parl_io.rs
  esp-hal/src/rmt.rs
  esp-hal/src/spi/master.rs
Labels: skip-changelog

#2279 Add GPIO Matrix support to Camera driver
  esp-hal/src/lcd_cam/cam.rs
Labels: skip-changelog

#2276 I2C: clean up and remove stop condition from the middle of `write_read`
  esp-hal/src/i2c.rs
  hil-test/tests/i2c.rs
Labels: skip-changelog

#2284 Change `debug!` to `trace!` to reduce logging noise
  esp-wifi/src/ble/btdm.rs
  esp-wifi/src/ble/npl.rs
  esp-wifi/src/ble/os_adapter_esp32.rs
  esp-wifi/src/ble/os_adapter_esp32c3.rs
  esp-wifi/src/ble/os_adapter_esp32c6.rs
  esp-wifi/src/ble/os_adapter_esp32h2.rs
  esp-wifi/src/ble/os_adapter_esp32s3.rs
  esp-wifi/src/compat/timer_compat.rs
  esp-wifi/src/tasks.rs
Labels: skip-changelog

#2268 Add DMA buffer view support to I8080 driver
  esp-hal/src/lcd_cam/lcd/i8080.rs
Labels: skip-changelog

#2290 Clean up `impl_dma_eligible`
  esp-hal/src/peripheral.rs
Labels: skip-changelog

#2292 Fix typo
  esp-hal/src/rtc_cntl/mod.rs
Labels: skip-changelog

#2303 bump all semver compatible deps
  esp-backtrace/Cargo.toml
  esp-build/Cargo.toml
  esp-hal-embassy/Cargo.toml
  esp-hal-procmacros/Cargo.toml
  esp-hal/Cargo.toml
  esp-metadata/Cargo.toml
  esp-println/Cargo.toml
  esp-storage/Cargo.toml
  esp-wifi/Cargo.toml
  examples/Cargo.toml
  hil-test/Cargo.toml
  xtask/Cargo.toml
  xtensa-lx-rt/Cargo.toml
  xtensa-lx/Cargo.toml
Labels: skip-changelog

#2288 Slight TWAI corrections
  esp-hal/src/soc/esp32c3/efuse/fields.rs
  esp-hal/src/soc/esp32s3/efuse/fields.rs
  esp-hal/src/twai/mod.rs
  examples/src/bin/embassy_twai.rs
  examples/src/bin/twai.rs
Labels: skip-changelog

#2306 Remove unused dependencies
  esp-hal-embassy/Cargo.toml
  esp-ieee802154/Cargo.toml
  esp-lp-hal/Cargo.toml
  esp-wifi/Cargo.toml
  examples/Cargo.toml
Labels: skip-changelog

#2308 Reimplement SPI DMA operations in terms of transfer
  esp-hal/src/dma/buffers.rs
  esp-hal/src/spi/master.rs
Labels: skip-changelog

#2317 Clean up warnings
  esp-hal/src/dma/buffers.rs
  esp-ieee802154/src/raw.rs
Labels: skip-changelog

#2318 Fix first UART print
  esp-hal/src/uart.rs
  hil-test/Cargo.toml
  hil-test/tests/uart_regression.rs
Labels: skip-changelog

#2320 I2c rename, small docs clean up
  esp-hal/CHANGELOG.md
  esp-hal/MIGRATING-0.20.md
  esp-hal/src/clock/mod.rs
  esp-hal/src/gpio/mod.rs
  esp-hal/src/i2c.rs
  esp-hal/src/lib.rs
  esp-hal/src/prelude.rs
  esp-hal/src/rtc_cntl/mod.rs
  esp-hal/src/soc/esp32/cpu_control.rs
  esp-wifi/src/lib.rs
  examples/src/bin/embassy_i2c.rs
  examples/src/bin/embassy_i2c_bmp180_calibration_data.rs
  examples/src/bin/i2c_bmp180_calibration_data.rs
  examples/src/bin/i2c_display.rs
  examples/src/bin/lcd_cam_ov2640.rs
  hil-test/tests/i2c.rs
Labels: skip-changelog

#2322 Require float-save-restore in esp-wifi
  esp-wifi/Cargo.toml
  esp-wifi/src/preempt/mod.rs
  esp-wifi/src/preempt/preempt_riscv.rs
  esp-wifi/src/preempt/preempt_xtensa.rs
  hil-test/Cargo.toml
  hil-test/tests/esp_wifi_floats.rs
Labels: skip-changelog

#2310 New package releases
  esp-alloc/CHANGELOG.md
  esp-alloc/Cargo.toml
  esp-backtrace/CHANGELOG.md
  esp-backtrace/Cargo.toml
  esp-build/Cargo.toml
  esp-config/Cargo.toml
  esp-hal-embassy/CHANGELOG.md
  esp-hal-embassy/Cargo.toml
  esp-hal-embassy/MIGRATING-0.3.md
  esp-hal-procmacros/Cargo.toml
  esp-hal/CHANGELOG.md
  esp-hal/Cargo.toml
  esp-hal/MIGRATING-0.20.md
  esp-ieee802154/CHANGELOG.md
  esp-ieee802154/Cargo.toml
  esp-lp-hal/Cargo.toml
  esp-metadata/Cargo.toml
  esp-println/CHANGELOG.md
  esp-println/Cargo.toml
  esp-storage/CHANGELOG.md
  esp-storage/Cargo.toml
  esp-wifi/CHANGELOG.md
  esp-wifi/Cargo.toml
  esp-wifi/MIGRATING-0.9.md
Labels: skip-changelog

#2327 Add new living migration guides
  esp-hal-embassy/MIGRATING-0.4.md
  esp-hal/MIGRATING-0.21.md
  esp-wifi/MIGRATING-0.10.md
Labels: skip-changelog

#2333 Fix esp-wifi docs
  xtask/src/lib.rs
Labels: skip-changelog

#2332 Silence clippy
  esp-wifi/src/lib.rs
Labels: skip-changelog

#2287 XTASK: add a way to activate features per chip (docs)
  xtask/src/lib.rs
Labels: skip-changelog

#2323 Move mem2mem out of GDMA module
  esp-hal/src/dma/gdma.rs
  esp-hal/src/dma/m2m.rs
  esp-hal/src/dma/mod.rs
Labels: skip-changelog

#2349 Point to `Config` usage examples
  esp-hal/src/config.rs
  esp-hal/src/lib.rs
Labels: documentation, skip-changelog

#2351 Add `--fix` to `lint-packages`
  esp-hal/src/uart.rs
  xtask/src/main.rs
Labels: skip-changelog, automation

#2354 `esp-wifi` docs improve
  esp-wifi/src/ble/btdm.rs
  esp-wifi/src/common_adapter/common_adapter_esp32c3.rs
  esp-wifi/src/common_adapter/common_adapter_esp32c6.rs
  esp-wifi/src/common_adapter/common_adapter_esp32s3.rs
  esp-wifi/src/compat/common.rs
  esp-wifi/src/compat/timer_compat.rs
  esp-wifi/src/esp_now/mod.rs
  esp-wifi/src/preempt/mod.rs
  esp-wifi/src/preempt/preempt_riscv.rs
  esp-wifi/src/preempt/preempt_xtensa.rs
  esp-wifi/src/tasks.rs
  esp-wifi/src/timer/mod.rs
  esp-wifi/src/timer/riscv.rs
  esp-wifi/src/timer/timer_esp32.rs
  esp-wifi/src/timer/timer_esp32c2.rs
  esp-wifi/src/timer/timer_esp32c3.rs
  esp-wifi/src/timer/timer_esp32c6.rs
  esp-wifi/src/timer/timer_esp32h2.rs
  esp-wifi/src/timer/timer_esp32s2.rs
  esp-wifi/src/timer/timer_esp32s3.rs
  esp-wifi/src/timer/xtensa.rs
  esp-wifi/src/wifi/mod.rs
  esp-wifi/src/wifi_interface.rs
Labels: skip-changelog

#2363 fix doc
  esp-wifi/MIGRATING-0.9.md
Labels: skip-changelog

#2378 PAC update
  esp-hal/Cargo.toml
  esp-hal/src/gpio/lp_io.rs
  esp-hal/src/i2c.rs
  esp-hal/src/twai/mod.rs
  esp-hal/src/uart.rs
Labels: skip-changelog

#2383 Update PACs to latest git revision
  esp-hal/Cargo.toml
  esp-hal/src/rsa/esp32cX.rs
  esp-hal/src/rsa/esp32sX.rs
  esp-hal/src/rsa/mod.rs
  esp-hal/src/twai/mod.rs
Labels: skip-changelog

#2384 GPIO cleanup
  esp-hal/src/gpio/interconnect.rs
  esp-hal/src/gpio/mod.rs
  esp-hal/src/gpio/placeholder.rs
  esp-hal/src/gpio/rtc_io.rs
Labels: skip-changelog

#2394 Clean up i2c add_cmd
  esp-hal/src/i2c.rs
Labels: skip-changelog

#2395 Add note to start_app_core
  esp-hal/src/soc/esp32/cpu_control.rs
  esp-hal/src/soc/esp32s3/cpu_control.rs
Labels: documentation, skip-changelog

#2397 Wait more before re-enabling USB power
  .github/workflows/hil.yml
Labels: CI, skip-changelog

#2393 Fix esp-hal-embassy 0.3 migration guide
  esp-hal-embassy/MIGRATING-0.3.md
Labels: skip-changelog

#2402 Use `panic` instead of `process::exit` in `esp-build`
  esp-build/src/lib.rs
Labels: skip-changelog

#2400 Rework how pin capabilities are declared
  esp-hal/src/gpio/mod.rs
  esp-hal/src/soc/esp32/gpio.rs
  esp-hal/src/soc/esp32c2/gpio.rs
  esp-hal/src/soc/esp32c3/gpio.rs
  esp-hal/src/soc/esp32c6/gpio.rs
  esp-hal/src/soc/esp32h2/gpio.rs
  esp-hal/src/soc/esp32s2/gpio.rs
  esp-hal/src/soc/esp32s3/gpio.rs
Labels: skip-changelog

#2405 Small SPI slave cleanup
  esp-hal/src/spi/slave.rs
Labels: skip-changelog

#2411 Add `Cpu::COUNT` and clean up in `esp-hal-embassy`
  esp-hal-embassy/src/executor/interrupt.rs
  esp-hal-embassy/src/executor/mod.rs
  esp-hal-embassy/src/executor/thread.rs
  esp-hal/CHANGELOG.md
  esp-hal/src/lib.rs
Labels: skip-changelog

#2404 Merge/remove some GPIO-related macros
  esp-hal/src/gpio/lp_io.rs
  esp-hal/src/gpio/mod.rs
  esp-hal/src/soc/esp32/gpio.rs
  esp-hal/src/soc/esp32c2/gpio.rs
  esp-hal/src/soc/esp32c3/gpio.rs
  esp-hal/src/soc/esp32c6/gpio.rs
  esp-hal/src/soc/esp32h2/gpio.rs
  esp-hal/src/soc/esp32s2/gpio.rs
  esp-hal/src/soc/esp32s3/gpio.rs
Labels: skip-changelog

#2425 RISC-V: Fix interrupt stack alignment
  esp-riscv-rt/src/lib.rs
Labels: skip-changelog

#2429 Move some implementation details out of GPIO
  esp-hal/src/gpio/mod.rs
  esp-hal/src/soc/esp32/gpio.rs
  esp-hal/src/soc/esp32c2/gpio.rs
  esp-hal/src/soc/esp32c3/gpio.rs
  esp-hal/src/soc/esp32s2/gpio.rs
  esp-hal/src/soc/esp32s3/gpio.rs
Labels: skip-changelog

#2410 Reduce UART Instance trait to the bare minimum
  esp-hal/src/uart.rs
Labels: skip-changelog

#2435 Fix typo in migration guide
  esp-hal/MIGRATING-0.20.md
Labels: skip-changelog

#2438 Use latest PAC rev which aligns TWAI field names
  esp-hal/Cargo.toml
  esp-hal/src/twai/mod.rs
Labels: skip-changelog

#2439 Disable i2s test
  hil-test/tests/i2s.rs
Labels: skip-changelog
