Repository esp-rs/esp-hal, pull requests merged in 2024-08, with the labels that each got.

#1886 esp-hal: Add HIL test for embassy timer and executor
  hil-test/Cargo.toml
  hil-test/tests/embassy_timers_executors.rs
Labels: skip-changelog

#1901 Deny Rust 2018 idioms in `esp-hal`
  esp-hal/src/aes/mod.rs
  esp-hal/src/delay.rs
  esp-hal/src/dma/gdma.rs
  esp-hal/src/i2c.rs
  esp-hal/src/i2s.rs
  esp-hal/src/lcd_cam/cam.rs
  esp-hal/src/lcd_cam/lcd/i8080.rs
  esp-hal/src/ledc/mod.rs
  esp-hal/src/ledc/timer.rs
  esp-hal/src/lib.rs
  esp-hal/src/mcpwm/mod.rs
  esp-hal/src/mcpwm/timer.rs
  esp-hal/src/parl_io.rs
  esp-hal/src/pcnt/unit.rs
  esp-hal/src/rmt.rs
  esp-hal/src/rsa/esp32.rs
  esp-hal/src/rsa/esp32cX.rs
  esp-hal/src/rsa/esp32sX.rs
  esp-hal/src/rtc_cntl/sleep/esp32.rs
  esp-hal/src/rtc_cntl/sleep/esp32c3.rs
  esp-hal/src/rtc_cntl/sleep/esp32c6.rs
  esp-hal/src/rtc_cntl/sleep/esp32s3.rs
  esp-hal/src/rtc_cntl/sleep/mod.rs
  esp-hal/src/spi/master.rs
  esp-hal/src/spi/slave.rs
  esp-hal/src/timer/timg.rs
  esp-hal/src/touch.rs
  esp-hal/src/twai/mod.rs
  esp-hal/src/uart.rs
Labels: skip-changelog

#1881 Check packages with nightly for RISC-V devices
  .github/actions/check-esp-hal/action.yml
  .github/workflows/ci.yml
  .github/workflows/ci_nightly.yml
  .github/workflows/hil.yml
  xtask/src/main.rs
Labels: skip-changelog

#1900 Removing unnecessary `bitfield` from `I2C` driver
  esp-hal/Cargo.toml
  esp-hal/src/i2c.rs
Labels: skip-changelog

#1911 Make `C6` ADC calibration work properly again
  esp-hal/src/clock/clocks_ll/esp32c6.rs
  examples/src/bin/adc_cal.rs
Labels: skip-changelog

#1930 Fix some typos
  esp-hal/src/analog/adc/mod.rs
  esp-hal/src/dma/mod.rs
  esp-hal/src/gpio/etm.rs
  esp-hal/src/rsa/esp32sX.rs
  hil-test/tests/embassy_timers_executors.rs
Labels: skip-changelog

#1940 Fix `i2c` + get rid of unused constants/enums
  esp-hal/Cargo.toml
  esp-hal/src/i2c.rs
Labels: skip-changelog

#1937 Slightly clean up embassy HIL tests
  hil-test/tests/embassy_timers_executors.rs
Labels: skip-changelog

#1946 Adding `TWAI` HIL test
  hil-test/Cargo.toml
  hil-test/tests/twai.rs
Labels: skip-changelog

#1939 Update probe-rs, prebuild xtask for HIL tests
  .github/workflows/hil.yml
  hil-test/README.md
  hil-test/tests/get_time.rs
  xtask/src/lib.rs
  xtask/src/main.rs
Labels: skip-changelog

#1892 Removing raw addresses manipulations - part 3
  esp-hal/Cargo.toml
  esp-hal/src/interrupt/riscv.rs
  esp-hal/src/rtc_cntl/sleep/esp32c3.rs
  esp-hal/src/rtc_cntl/sleep/esp32s3.rs
  esp-hal/src/soc/esp32c6/radio_clocks.rs
  esp-hal/src/soc/esp32h2/radio_clocks.rs
  esp-wifi/src/wifi/os_adapter_esp32.rs
Labels: skip-changelog

#1947 Make contribution docs more visible
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  documentation/API-GUIDELINES.md
  documentation/CONTRIBUTING.md
Labels: skip-changelog

#1951 Clean up i2s_async test, add option to repeat
  esp-hal/src/i2s.rs
  hil-test/.cargo/config.toml
  hil-test/tests/i2s_async.rs
  xtask/src/cargo.rs
  xtask/src/lib.rs
  xtask/src/main.rs
Labels: skip-changelog

#1953 Further clean up timers/executors test
  hil-test/tests/embassy_timers_executors.rs
Labels: skip-changelog

#1957 Simplify initialization APIs
  esp-hal-embassy/CHANGELOG.md
  esp-hal-embassy/Cargo.toml
  esp-hal-embassy/src/lib.rs
  esp-hal/src/lib.rs
  esp-hal/src/timer/timg.rs
  esp-wifi/CHANGELOG.md
  esp-wifi/Cargo.toml
  esp-wifi/README.md
  esp-wifi/build.rs
  esp-wifi/src/lib.rs
  esp-wifi/src/timer/mod.rs
  esp-wifi/src/timer/riscv.rs
  esp-wifi/src/timer/xtensa.rs
  examples/src/bin/embassy_hello_world.rs
  examples/src/bin/embassy_i2c.rs
  examples/src/bin/embassy_i2c_bmp180_calibration_data.rs
  examples/src/bin/embassy_i2s_read.rs
  examples/src/bin/embassy_i2s_sound.rs
  examples/src/bin/embassy_multiprio.rs
  examples/src/bin/embassy_parl_io_rx.rs
  examples/src/bin/embassy_parl_io_tx.rs
  examples/src/bin/embassy_rmt_rx.rs
  examples/src/bin/embassy_rmt_tx.rs
  examples/src/bin/embassy_serial.rs
  examples/src/bin/embassy_spi.rs
  examples/src/bin/embassy_touch.rs
  examples/src/bin/embassy_twai.rs
  examples/src/bin/embassy_usb_serial.rs
  examples/src/bin/embassy_usb_serial_jtag.rs
  examples/src/bin/embassy_wait.rs
  examples/src/bin/wifi_access_point.rs
  examples/src/bin/wifi_access_point_with_sta.rs
  examples/src/bin/wifi_bench.rs
  examples/src/bin/wifi_ble.rs
  examples/src/bin/wifi_coex.rs
  examples/src/bin/wifi_dhcp.rs
  examples/src/bin/wifi_embassy_access_point.rs
  examples/src/bin/wifi_embassy_access_point_with_sta.rs
  examples/src/bin/wifi_embassy_bench.rs
  examples/src/bin/wifi_embassy_ble.rs
  examples/src/bin/wifi_embassy_dhcp.rs
  examples/src/bin/wifi_embassy_esp_now.rs
  examples/src/bin/wifi_embassy_esp_now_duplex.rs
  examples/src/bin/wifi_esp_now.rs
  examples/src/bin/wifi_static_ip.rs
  hil-test/tests/embassy_timers_executors.rs
  hil-test/tests/gpio.rs
Labels: skip-changelog

#1965 Some xtask/metadata cleanups
  esp-hal/build.rs
  esp-metadata/src/lib.rs
  resources/index.html.jinja
  xtask/src/main.rs
Labels: skip-changelog

#1952 Add more SPI DMA (full-duplex) HIL tests (blocking and async)
  hil-test/Cargo.toml
  hil-test/tests/spi_full_duplex_dma.rs
  hil-test/tests/spi_full_duplex_dma_async.rs
  hil-test/tests/spi_half_duplex_write.rs
Labels: skip-changelog

#1963 Add basic GPIO HIL test for `AnyPin` and touch pin
  hil-test/tests/gpio.rs
Labels: skip-changelog, tests

#1960 Disable RTT polling in HIL tests by default
  hil-test/Cargo.toml
  hil-test/README.md
  hil-test/src/lib.rs
  hil-test/tests/aes.rs
  hil-test/tests/aes_dma.rs
  hil-test/tests/clock_monitor.rs
  hil-test/tests/crc.rs
  hil-test/tests/delay.rs
  hil-test/tests/dma_macros.rs
  hil-test/tests/dma_mem2mem.rs
  hil-test/tests/ecc.rs
  hil-test/tests/embassy_interrupt_executor.rs
  hil-test/tests/embassy_timers_executors.rs
  hil-test/tests/get_time.rs
  hil-test/tests/gpio.rs
  hil-test/tests/i2s.rs
  hil-test/tests/i2s_async.rs
  hil-test/tests/interrupt.rs
  hil-test/tests/lcd_cam_i8080.rs
  hil-test/tests/lcd_cam_i8080_async.rs
  hil-test/tests/pcnt.rs
  hil-test/tests/rmt.rs
  hil-test/tests/rsa.rs
  hil-test/tests/sha.rs
  hil-test/tests/spi_full_duplex.rs
  hil-test/tests/spi_full_duplex_dma.rs
  hil-test/tests/spi_full_duplex_dma_async.rs
  hil-test/tests/spi_half_duplex_read.rs
  hil-test/tests/spi_half_duplex_write.rs
  hil-test/tests/twai.rs
  hil-test/tests/uart.rs
  hil-test/tests/uart_async.rs
  hil-test/tests/uart_tx_rx.rs
  hil-test/tests/uart_tx_rx_async.rs
  hil-test/tests/usb_serial_jtag.rs
Labels: skip-changelog, tests

#1959 Run HIL tests as part of PR checks
  .github/workflows/ci.yml
  .github/workflows/hil.yml
Labels: CI, skip-changelog

#1974 correct changelog sections
  esp-hal/CHANGELOG.md
Labels: skip-changelog

#1978 Add tests to ensure that we don't break `current_time`'s underlying driver
  esp-hal/src/system.rs
  esp-hal/src/timer/systimer.rs
  hil-test/Cargo.toml
  hil-test/build.rs
  hil-test/tests/get_time.rs
Labels: skip-changelog

#1988 tell cargo about all our custom cfgs
  esp-hal/Cargo.toml
  esp-hal/src/interrupt/riscv.rs
  esp-hal/src/system.rs
  esp-metadata/src/lib.rs
  hil-test/Cargo.toml
Labels: skip-changelog

#1997 Cycle USB port power before each test run
  .github/workflows/hil.yml
  hil-test/README.md
Labels: CI

#1993 HIL: Remove files after test
  .github/workflows/hil.yml
Labels: CI

#2000 Clean up SHA, RSA, mandate `#[must_use]` on Futures
  documentation/API-GUIDELINES.md
  esp-hal/src/aes/mod.rs
  esp-hal/src/analog/adc/mod.rs
  esp-hal/src/dma/mod.rs
  esp-hal/src/gpio/mod.rs
  esp-hal/src/i2c.rs
  esp-hal/src/lcd_cam/mod.rs
  esp-hal/src/parl_io.rs
  esp-hal/src/rmt.rs
  esp-hal/src/rsa/esp32.rs
  esp-hal/src/rsa/esp32cX.rs
  esp-hal/src/rsa/esp32sX.rs
  esp-hal/src/rsa/mod.rs
  esp-hal/src/sha.rs
  esp-hal/src/timer/systimer.rs
  esp-hal/src/touch.rs
  esp-hal/src/twai/mod.rs
  esp-hal/src/uart.rs
  esp-hal/src/usb_serial_jtag.rs
  esp-wifi/src/ble/controller/mod.rs
  esp-wifi/src/esp_now/mod.rs
  esp-wifi/src/wifi/mod.rs
  hil-test/tests/aes.rs
  hil-test/tests/aes_dma.rs
  hil-test/tests/sha.rs
Labels: skip-changelog

#2003 Prefer `cfg_if`
  documentation/API-GUIDELINES.md
  esp-hal-embassy/src/executor/thread.rs
  esp-hal/src/aes/mod.rs
  esp-hal/src/analog/adc/mod.rs
  esp-hal/src/clock/mod.rs
  esp-hal/src/dma/mod.rs
  esp-hal/src/gpio/mod.rs
  esp-hal/src/i2c.rs
  esp-hal/src/interrupt/mod.rs
  esp-hal/src/ledc/mod.rs
  esp-hal/src/mcpwm/mod.rs
  esp-hal/src/peripheral.rs
  esp-hal/src/rmt.rs
  esp-hal/src/rom/md5.rs
  esp-hal/src/rtc_cntl/mod.rs
  esp-hal/src/soc/esp32/efuse/mod.rs
  esp-hal/src/soc/esp32c2/efuse/mod.rs
  esp-hal/src/soc/esp32c3/efuse/mod.rs
  esp-hal/src/soc/esp32c6/efuse/mod.rs
  esp-hal/src/soc/esp32h2/efuse/mod.rs
  esp-hal/src/soc/esp32s2/efuse/mod.rs
  esp-hal/src/soc/esp32s3/efuse/mod.rs
  esp-hal/src/spi/master.rs
  esp-hal/src/spi/slave.rs
  esp-hal/src/timer/mod.rs
  esp-hal/src/timer/systimer.rs
  esp-hal/src/timer/timg.rs
  esp-hal/src/twai/filter.rs
  esp-hal/src/twai/mod.rs
  esp-hal/src/usb_serial_jtag.rs
  examples/src/bin/embassy_multiprio.rs
  examples/src/bin/embassy_serial.rs
  examples/src/bin/embassy_spi.rs
  examples/src/bin/gpio_interrupt.rs
  examples/src/bin/hello_rgb.rs
  examples/src/bin/hello_world.rs
  examples/src/bin/ieee802154_sniffer.rs
  examples/src/bin/mcpwm.rs
  examples/src/bin/qspi_flash.rs
  examples/src/bin/serial_interrupts.rs
  examples/src/bin/sleep_timer_rtcio.rs
  examples/src/bin/spi_loopback_dma.rs
  examples/src/bin/wifi_ble.rs
  examples/src/bin/wifi_embassy_access_point.rs
  examples/src/bin/wifi_embassy_access_point_with_sta.rs
  examples/src/bin/wifi_embassy_bench.rs
  examples/src/bin/wifi_embassy_ble.rs
  examples/src/bin/wifi_embassy_dhcp.rs
  examples/src/bin/wifi_embassy_esp_now.rs
  examples/src/bin/wifi_embassy_esp_now_duplex.rs
  hil-test/tests/clock_monitor.rs
  hil-test/tests/dma_mem2mem.rs
  hil-test/tests/gpio.rs
  hil-test/tests/rsa.rs
Labels: skip-changelog

#2011 Re-add feature gate for software_interrupt3
  esp-hal-embassy/Cargo.toml
  esp-hal/CHANGELOG.md
  esp-hal/Cargo.toml
  esp-hal/src/system.rs
Labels: skip-changelog

#2013 Fix QSPI
  esp-hal/src/spi/master.rs
Labels: skip-changelog

#2014 Only reserve the interrupt when executors are needed
  esp-hal-embassy/Cargo.toml
Labels: skip-changelog

#2017 Fix defmt compatibility
  esp-hal/src/dma/mod.rs
  hil-test/tests/i2s_async.rs
  hil-test/tests/spi_half_duplex_write.rs
Labels: skip-changelog

#2022 Remove unneeded logs
  esp-hal/CHANGELOG.md
Labels: skip-changelog

#2024 HIL: Don't skip cleanup
  .github/workflows/hil.yml
Labels: CI

#2038 Version 0.20.0
  esp-backtrace/CHANGELOG.md
  esp-backtrace/Cargo.toml
  esp-hal-embassy/CHANGELOG.md
  esp-hal-embassy/Cargo.toml
  esp-hal-procmacros/Cargo.toml
  esp-hal-smartled/CHANGELOG.md
  esp-hal-smartled/Cargo.toml
  esp-hal/CHANGELOG.md
  esp-hal/Cargo.toml
  esp-ieee802154/CHANGELOG.md
  esp-ieee802154/Cargo.toml
  esp-lp-hal/Cargo.toml
  esp-metadata/Cargo.toml
  esp-println/CHANGELOG.md
  esp-println/Cargo.toml
  esp-wifi/CHANGELOG.md
  esp-wifi/Cargo.toml
  esp-wifi/src/preempt/preempt_xtensa.rs
  hil-test/Cargo.toml
  xtensa-lx-rt/Cargo.toml
  xtensa-lx-rt/src/exception/context.rs
Labels: skip-changelog

#2040 Fix before_snippet failing in release
  esp-hal-embassy/src/executor/thread.rs
  esp-hal/build.rs
  esp-hal/doc-helper/before
  esp-hal/src/lib.rs
  esp-hal/src/mcpwm/operator.rs
Labels: skip-changelog

#1934 Fix nightly CI errors
  esp-backtrace/src/riscv.rs
  esp-hal/src/soc/esp32c6/efuse/fields.rs
  esp-lp-hal/src/uart.rs
  esp-wifi/src/common_adapter/mod.rs
  esp-wifi/src/esp_now/mod.rs
  examples/src/bin/debug_assist.rs
  examples/src/bin/embassy_usb_serial_jtag.rs
  xtensa-lx/src/lib.rs
Labels: skip-changelog

#2018 Disable object's unnecessary features in proc macro that loads LP code
  esp-hal-procmacros/Cargo.toml
Labels: skip-changelog

#2034 Random cleanups in non-checked packages
  .github/workflows/hil.yml
  esp-build/src/lib.rs
  esp-hal-procmacros/src/embassy.rs
  esp-hal-procmacros/src/enum_dispatch.rs
  esp-hal-procmacros/src/interrupt.rs
  esp-hal-procmacros/src/lib.rs
  esp-hal-procmacros/src/lp_core.rs
  esp-lp-hal/Cargo.toml
  extras/bench-server/src/main.rs
  xtask/src/lib.rs
  xtask/src/main.rs
Labels: skip-changelog
