Repository esp-rs/esp-hal, pull requests merged in 2024-11, with the labels that each got.

#2337 Add check owner support to DMA buffers
  esp-hal/src/dma/buffers.rs
  esp-hal/src/dma/gdma.rs
  esp-hal/src/dma/mod.rs
  esp-hal/src/dma/pdma.rs
Labels: skip-changelog

#2301 Remove `EspWifiInitFor` & more granular init/deinit per driver
  esp-hal/src/rng.rs
  esp-wifi/CHANGELOG.md
  esp-wifi/Cargo.toml
  esp-wifi/MIGRATING-0.10.md
  esp-wifi/src/ble/btdm.rs
  esp-wifi/src/ble/controller/mod.rs
  esp-wifi/src/ble/mod.rs
  esp-wifi/src/ble/npl.rs
  esp-wifi/src/compat/misc.rs
  esp-wifi/src/esp_now/mod.rs
  esp-wifi/src/lib.rs
  esp-wifi/src/timer/mod.rs
  esp-wifi/src/timer/riscv.rs
  esp-wifi/src/timer/xtensa.rs
  esp-wifi/src/wifi/mod.rs
  esp-wifi/src/wifi/utils.rs
  examples/Cargo.toml
  examples/src/bin/wifi_80211_tx.rs
  examples/src/bin/wifi_access_point.rs
  examples/src/bin/wifi_access_point_with_sta.rs
  examples/src/bin/wifi_bench.rs
  examples/src/bin/wifi_ble.rs
  examples/src/bin/wifi_coex.rs
  examples/src/bin/wifi_dhcp.rs
  examples/src/bin/wifi_embassy_access_point.rs
  examples/src/bin/wifi_embassy_access_point_with_sta.rs
  examples/src/bin/wifi_embassy_bench.rs
  examples/src/bin/wifi_embassy_ble.rs
  examples/src/bin/wifi_embassy_dhcp.rs
  examples/src/bin/wifi_embassy_esp_now.rs
  examples/src/bin/wifi_embassy_esp_now_duplex.rs
  examples/src/bin/wifi_embassy_trouble.rs
  examples/src/bin/wifi_esp_now.rs
  examples/src/bin/wifi_sniffer.rs
  examples/src/bin/wifi_static_ip.rs
  hil-test/tests/esp_wifi_floats.rs
Labels: skip-changelog

#2459 Remove redundant lifetimes
  esp-hal/src/dma/m2m.rs
Labels: skip-changelog

#2462 Prefer ROM-fns over custom impl
  esp-hal/ld/esp32/rom/additional.ld
  esp-hal/ld/esp32c2/rom/additional.ld
  esp-hal/ld/esp32c3/rom/additional.ld
  esp-hal/ld/esp32c6/rom/additional.ld
  esp-hal/ld/esp32h2/rom/additional.ld
  esp-hal/ld/esp32s2/rom/additional.ld
  esp-hal/ld/esp32s3/rom/additional.ld
  esp-wifi/CHANGELOG.md
  esp-wifi/Cargo.toml
  esp-wifi/src/compat/misc.rs
Labels: skip-changelog

#2465 Use `diagnostic` on `DmaChannelConvert`
  esp-hal/src/dma/mod.rs
Labels: skip-changelog

#2471 Mark State/Info as `#[non_exhaustive]`
  esp-hal/src/spi/master.rs
  esp-hal/src/uart.rs
Labels: skip-changelog

#2470 SPI slave: remove public hidden API
  esp-hal/src/spi/slave.rs
Labels: skip-changelog

#2468 Remove PeripheralMarker
  esp-hal/src/dma/gdma.rs
  esp-hal/src/dma/mod.rs
  esp-hal/src/dma/pdma.rs
  esp-hal/src/i2c.rs
  esp-hal/src/i2s/master.rs
  esp-hal/src/i2s/parallel.rs
  esp-hal/src/macros.rs
  esp-hal/src/peripheral.rs
  esp-hal/src/soc/esp32/peripherals.rs
  esp-hal/src/soc/esp32c2/peripherals.rs
  esp-hal/src/soc/esp32c3/peripherals.rs
  esp-hal/src/soc/esp32c6/peripherals.rs
  esp-hal/src/soc/esp32h2/peripherals.rs
  esp-hal/src/soc/esp32s2/peripherals.rs
  esp-hal/src/soc/esp32s3/peripherals.rs
  esp-hal/src/spi/master.rs
  esp-hal/src/spi/slave.rs
  esp-hal/src/twai/mod.rs
  esp-hal/src/uart.rs
Labels: skip-changelog

#2483 Fix test warnings
  hil-test/tests/spi_full_duplex.rs
Labels: skip-changelog

#2482 Tweak guidelines
  documentation/API-GUIDELINES.md
Labels: documentation, skip-changelog

#2490 Test more embassy interrupt spi dma
  hil-test/tests/embassy_interrupt_spi_dma.rs
Labels: skip-changelog

#2480 I2C: move code into Driver
  esp-hal/src/i2c/master/mod.rs
Labels: skip-changelog

#2515 Update revision of PACs and fix all build errors
  esp-hal/Cargo.toml
  esp-hal/src/aes/esp32.rs
  esp-hal/src/aes/esp32cX.rs
  esp-hal/src/aes/esp32s2.rs
  esp-hal/src/aes/esp32s3.rs
  esp-hal/src/clock/clocks_ll/esp32c6.rs
  esp-hal/src/dma/gdma.rs
  esp-hal/src/dma/pdma.rs
  esp-hal/src/i2c/master/mod.rs
  esp-hal/src/interrupt/software.rs
  esp-hal/src/mcpwm/operator.rs
  esp-hal/src/rsa/esp32cX.rs
  esp-hal/src/rsa/esp32sX.rs
  esp-hal/src/rtc_cntl/mod.rs
  esp-hal/src/rtc_cntl/rtc/esp32c6.rs
  esp-hal/src/rtc_cntl/rtc/esp32h2.rs
  esp-hal/src/soc/esp32c6/lp_core.rs
  esp-hal/src/soc/esp32s3/psram.rs
  esp-hal/src/timer/timg.rs
  esp-hal/src/usb_serial_jtag.rs
  esp-ieee802154/src/hal.rs
Labels: skip-changelog

#2514 Modify `bump-version` subcommand to also bump dependent packages' dependencies
  xtask/src/lib.rs
Labels: skip-changelog

#2475 Add validation to `esp-config`
  esp-config/src/generate.rs
  esp-config/src/lib.rs
  esp-hal-embassy/build.rs
  esp-hal/build.rs
  esp-ieee802154/build.rs
  esp-wifi/build.rs
Labels: skip-changelog

#2530 Use newest published PACs
  esp-hal/Cargo.toml
Labels: skip-changelog

#2533 Remove `get_core()` in favour of `Cpu::current()`
  esp-hal-embassy/src/executor/interrupt.rs
  esp-hal-embassy/src/executor/thread.rs
  esp-hal/CHANGELOG.md
  esp-hal/MIGRATING-0.21.md
  esp-hal/src/interrupt/riscv.rs
  esp-hal/src/interrupt/xtensa.rs
  esp-hal/src/lib.rs
  esp-hal/src/reset.rs
  esp-hal/src/soc/esp32/cpu_control.rs
  esp-hal/src/soc/esp32/gpio.rs
  esp-hal/src/soc/esp32s3/cpu_control.rs
  examples/src/bin/embassy_multicore.rs
  examples/src/bin/embassy_multicore_interrupt.rs
Labels: skip-changelog

#2535 Update documentation to recommend `esp-generate` instead of `esp-template`
  esp-hal/src/lib.rs
  esp-hal/src/soc/esp32/mod.rs
  esp-hal/src/soc/esp32c2/mod.rs
  esp-hal/src/soc/esp32c3/mod.rs
  esp-hal/src/soc/esp32c6/mod.rs
  esp-hal/src/soc/esp32h2/mod.rs
  esp-hal/src/soc/esp32s2/mod.rs
  esp-hal/src/soc/esp32s3/mod.rs
Labels: skip-changelog

#2536 Use correct toolchain when building documentation or running doctests via xtask
  xtask/src/lib.rs
  xtask/src/main.rs
Labels: skip-changelog

#2521 [DMA 2/N] Split DMA IN/OUT handlers
  esp-hal/src/dma/gdma.rs
  esp-hal/src/dma/mod.rs
  esp-hal/src/dma/pdma.rs
  esp-hal/src/lib.rs
Labels: skip-changelog

#2560 Add missing Sealed impl
  esp-wifi/src/lib.rs
  hil-test/tests/esp_wifi_floats.rs
Labels: skip-changelog

#2561 Touch up the migration guide for esp-wifi
  esp-wifi/MIGRATING-0.10.md
Labels: skip-changelog

#2551 Avoid polling for no reason
  esp-hal-embassy/src/executor/thread.rs
Labels: skip-changelog

#2564 Remove some unnecessary prelude reexports
  esp-hal/src/prelude.rs
  hil-test/tests/uart_regression.rs
Labels: skip-changelog

#2565 Clarify embassy migration guide
  esp-hal-embassy/MIGRATING-0.4.md
Labels: documentation, skip-changelog

#2563 Add pin driver examples, explain drivers a bit better
  esp-hal/src/gpio/mod.rs
  esp-hal/src/macros.rs
Labels: documentation, skip-changelog, peripheral:gpio

#2569 New package releases
  esp-config/CHANGELOG.md
  esp-config/Cargo.toml
  esp-hal-embassy/CHANGELOG.md
  esp-hal-embassy/Cargo.toml
  esp-hal-procmacros/CHANGELOG.md
  esp-hal-procmacros/Cargo.toml
  esp-hal/CHANGELOG.md
  esp-hal/Cargo.toml
  esp-ieee802154/CHANGELOG.md
  esp-ieee802154/Cargo.toml
  esp-lp-hal/Cargo.toml
  esp-riscv-rt/CHANGELOG.md
  esp-riscv-rt/Cargo.toml
  esp-storage/CHANGELOG.md
  esp-storage/Cargo.toml
  esp-wifi/CHANGELOG.md
  esp-wifi/Cargo.toml
  xtensa-lx-rt/CHANGELOG.md
  xtensa-lx-rt/Cargo.toml
Labels: skip-changelog

#2573 API guideline touchups
  documentation/API-GUIDELINES.md
Labels: skip-changelog

#2578 Replace old API in SPI example in migration guide
  esp-hal/MIGRATING-0.21.md
Labels: documentation, skip-changelog

#2571 Add new migration guides
  esp-hal-embassy/MIGRATING-0.5.md
  esp-hal/MIGRATING-0.22.md
  esp-wifi/MIGRATING-0.11.md
Labels: skip-changelog

#2585 SPI PDMA: Don't read to clear interrupts
  esp-hal/src/dma/pdma.rs
Labels: skip-changelog

#2576 [1/4] Timer refactor: system timer
  esp-hal-embassy/src/lib.rs
  esp-hal/CHANGELOG.md
  esp-hal/MIGRATING-0.22.md
  esp-hal/src/time.rs
  esp-hal/src/timer/mod.rs
  esp-hal/src/timer/systimer.rs
  esp-wifi/src/lib.rs
  examples/src/bin/embassy_multiprio.rs
  examples/src/bin/embassy_parl_io_rx.rs
  examples/src/bin/embassy_parl_io_tx.rs
  examples/src/bin/etm_blinky_systimer.rs
  examples/src/bin/hmac.rs
  examples/src/bin/systimer.rs
  examples/src/bin/wifi_embassy_access_point.rs
  examples/src/bin/wifi_embassy_access_point_with_sta.rs
  examples/src/bin/wifi_embassy_bench.rs
  examples/src/bin/wifi_embassy_ble.rs
  examples/src/bin/wifi_embassy_dhcp.rs
  examples/src/bin/wifi_embassy_esp_now.rs
  examples/src/bin/wifi_embassy_esp_now_duplex.rs
  examples/src/bin/wifi_embassy_trouble.rs
  examples/src/lib.rs
  hil-test/Cargo.toml
  hil-test/tests/delay_async.rs
  hil-test/tests/embassy_interrupt_executor.rs
  hil-test/tests/embassy_interrupt_spi_dma.rs
  hil-test/tests/embassy_timers_executors.rs
  hil-test/tests/systimer.rs
Labels: skip-changelog

#2527 [DMA 5/8]: Clean up macros
  esp-hal/src/dma/gdma.rs
  esp-hal/src/dma/mod.rs
  esp-hal/src/dma/pdma.rs
  esp-hal/src/macros.rs
  esp-hal/src/soc/esp32/gpio.rs
  esp-hal/src/soc/esp32s2/gpio.rs
  esp-hal/src/soc/esp32s3/gpio.rs
  esp-hal/src/spi/master.rs
Labels: skip-changelog

#2567 esp-println: avoid double locking when using auto
  esp-println/src/defmt.rs
  esp-println/src/lib.rs
Labels: skip-changelog

#2581 [2/3] Timer refactor: TIMG
  esp-hal-embassy/src/lib.rs
  esp-hal/CHANGELOG.md
  esp-hal/MIGRATING-0.22.md
  esp-hal/src/prelude.rs
  esp-hal/src/timer/mod.rs
  esp-hal/src/timer/timg.rs
  esp-wifi/src/lib.rs
  examples/src/bin/etm_timer.rs
  examples/src/bin/timer_interrupt.rs
Labels: skip-changelog

#2555 Add custom AtomicWaker and embassy-sync mutex implementation
  esp-hal/CHANGELOG.md
  esp-hal/Cargo.toml
  esp-hal/src/asynch.rs
  esp-hal/src/dma/gdma.rs
  esp-hal/src/dma/mod.rs
  esp-hal/src/dma/pdma.rs
  esp-hal/src/gpio/mod.rs
  esp-hal/src/i2c/master/mod.rs
  esp-hal/src/lcd_cam/mod.rs
  esp-hal/src/lib.rs
  esp-hal/src/parl_io.rs
  esp-hal/src/rmt.rs
  esp-hal/src/rsa/mod.rs
  esp-hal/src/sync.rs
  esp-hal/src/timer/systimer.rs
  esp-hal/src/timer/timg.rs
  esp-hal/src/touch.rs
  esp-hal/src/uart.rs
  esp-hal/src/usb_serial_jtag.rs
  esp-wifi/src/ble/controller/mod.rs
  esp-wifi/src/esp_now/mod.rs
  esp-wifi/src/wifi/mod.rs
Labels: skip-changelog

#2588 AES cleanups
  esp-hal/src/aes/esp32.rs
  esp-hal/src/aes/esp32cX.rs
  esp-hal/src/aes/esp32s2.rs
  esp-hal/src/aes/esp32s3.rs
  esp-hal/src/aes/mod.rs
Labels: skip-changelog

#2357 Trim down `xtensa-lx`
  esp-hal/src/uart.rs
  xtensa-lx-rt/Cargo.toml
  xtensa-lx/CHANGELOG.md
  xtensa-lx/Cargo.toml
  xtensa-lx/src/interrupt.rs
  xtensa-lx/src/lib.rs
  xtensa-lx/src/macros.rs
  xtensa-lx/src/mutex.rs
Labels: skip-changelog

#2546 Auto-initialize PSRAM
  esp-alloc/src/macros.rs
  esp-hal/CHANGELOG.md
  esp-hal/MIGRATING-0.22.md
  esp-hal/src/lib.rs
  esp-hal/src/soc/esp32/psram.rs
  esp-hal/src/soc/esp32s2/psram.rs
  esp-hal/src/soc/esp32s3/psram.rs
  esp-hal/src/soc/mod.rs
  esp-hal/src/soc/psram_common.rs
  examples/src/bin/dma_extmem2mem.rs
  examples/src/bin/psram_octal.rs
  examples/src/bin/psram_quad.rs
Labels: skip-changelog

#2592 0.21 Migration guide fixes
  esp-hal/MIGRATING-0.21.md
Labels: documentation, skip-changelog

#2595 API-GUIDELINES: note rustdoc linkage
  documentation/API-GUIDELINES.md
Labels: skip-changelog

#2554 Replace some esp-wifi critical sections with locks
  esp-wifi/src/compat/common.rs
  esp-wifi/src/compat/timer_compat.rs
  esp-wifi/src/lib.rs
  esp-wifi/src/preempt/mod.rs
  esp-wifi/src/tasks.rs
  esp-wifi/src/timer/mod.rs
  esp-wifi/src/timer/riscv.rs
  esp-wifi/src/timer/xtensa.rs
  esp-wifi/src/wifi/event.rs
  esp-wifi/src/wifi/mod.rs
  esp-wifi/src/wifi/os_adapter.rs
  esp-wifi/src/wifi/os_adapter_esp32.rs
  esp-wifi/src/wifi/os_adapter_esp32c2.rs
  esp-wifi/src/wifi/os_adapter_esp32c3.rs
  esp-wifi/src/wifi/os_adapter_esp32c6.rs
  esp-wifi/src/wifi/os_adapter_esp32h2.rs
  esp-wifi/src/wifi/os_adapter_esp32s2.rs
  esp-wifi/src/wifi/os_adapter_esp32s3.rs
  examples/src/bin/wifi_access_point.rs
  examples/src/bin/wifi_embassy_access_point.rs
Labels: skip-changelog

#2617 Amend rust guidelines
  documentation/API-GUIDELINES.md
Labels: skip-changelog

#2586 [3/3] Timer refactor: Timer driver mode, ETM support and erasure
  esp-hal-embassy/src/time_driver.rs
  esp-hal/CHANGELOG.md
  esp-hal/MIGRATING-0.22.md
  esp-hal/src/gpio/mod.rs
  esp-hal/src/timer/mod.rs
  esp-hal/src/timer/systimer.rs
  esp-hal/src/timer/timg.rs
  esp-hal/src/touch.rs
  esp-wifi/src/lib.rs
  examples/src/bin/etm_timer.rs
  hil-test/Cargo.toml
  hil-test/tests/delay_async.rs
  hil-test/tests/embassy_timers_executors.rs
  hil-test/tests/systimer.rs
Labels: skip-changelog

#2612 Fixed triggering a debug-assertion during scan
  esp-hal/Cargo.toml
  esp-hal/build.rs
  esp-hal/src/lib.rs
  esp-metadata/CHANGELOG.md
  esp-metadata/devices/esp32c6.toml
  esp-wifi/CHANGELOG.md
  esp-wifi/src/wifi/event.rs
  examples/Cargo.toml
  hil-test/Cargo.toml
  qa-test/Cargo.toml
Labels: skip-changelog

#2622 Use opt-level to detect debug profile
  examples/build.rs
Labels: skip-changelog
